StartupEvents.registry('fluid', event => {
//  event.create('thick_fluid')
//event.create('thin_fluid')
    //olor(0x00FFFF)
//    .displayName('Ammo reservation Potion')
//    .noBucket()
//    .noBlock()
/*event.create('thin_fluid')
    //0xE6810A)
    //olor(0x00FFFF)
    .displayName('Archery Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x7A5AB3)
    //olor(0x00FFFF)
    .displayName('Battle Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xF6A0C6)
    //olor(0x00FFFF)
    .displayName('Biome Sight Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x6B4836)
    //olor(0x00FFFF)
    .displayName('Builder Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x4745C9)
    //olor(0x00FFFF)
    .displayName('Calming Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x935D28)
    //olor(0x00FFFF)
    .displayName('Crate Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xA2381A)
    //olor(0x00FFFF)
    .displayName('Dangersense Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x898A86)
    //olor(0x00FFFF)
    .displayName('Endurance Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x1BA3D0)
    //olor(0x00FFFF)
    .displayName('Featherfall Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x208548)
    //olor(0x00FFFF)
    .displayName('Fishing Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x0C5785)
    //olor(0x00FFFF)
    .displayName('Flipper Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x1057A0)
    //olor(0x00FFFF)
    .displayName('Gills Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x7714E8)
    //olor(0x00FFFF)
    .displayName('Gravitation Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xD71CB0)
    //olor(0x00FFFF)
    .displayName('Greater Luck Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xC91F97)
    //olor(0x00FFFF)
    .displayName('Heartreach Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xCE5D11)
    //olor(0x00FFFF)
    .displayName('Hunter Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xFFA403)
    //olor(0x00FFFF)
    .displayName('Inferno Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x0E8E9A)
    //olor(0x00FFFF)
    .displayName('Invisibility Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xBDB938)
    //olor(0x00FFFF)
    .displayName('Ironskin Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x899AC2)
    //olor(0x00FFFF)
    .displayName('Lesser Luck Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x8E0A00)
    //olor(0x00FFFF)
    .displayName('Lifeforce Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x252A3B)
    //olor(0x00FFFF)
    .displayName('Luck Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x5d1eb2)
    //olor(0x00FFFF)
    .displayName('Magic Power Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xf5229e)
    //olor(0x00FFFF)
    .displayName('Mana regeneration Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x528487)
    //olor(0x00FFFF)
    .displayName('Mining Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x63920f)
    //olor(0x00FFFF)
    .displayName('Night Owl Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x4a3c83)
    //olor(0x00FFFF)
    .displayName('Obsidian Skin Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xc77703)
    //olor(0x00FFFF)
    .displayName('Rage Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xf8309b)
    //olor(0x00FFFF)
    .displayName('Regeneration Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xc3c916)
    //olor(0x00FFFF)
    .displayName('Shine Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x4e7c0a)
    //olor(0x00FFFF)
    .displayName('Sonar Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0xf9d74c)
    //olor(0x00FFFF)
    .displayName('Spelunker Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x6e811a)
    //olor(0x00FFFF)
    .displayName('Summoning Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x80da0b)
    //olor(0x00FFFF)
    .displayName('Swiftness Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x8aa911)
    //olor(0x00FFFF)
    .displayName('Thorns Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x60b232)
    //olor(0x00FFFF)
    .displayName('Titan Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x1f74e7)
    //olor(0x00FFFF)
    .displayName('Water Walking Potion')
    .noBucket()
    .noBlock()
event.create('thin_fluid')
    //0x872b24)
    //olor(0x00FFFF)
    .displayName('Wrath Potion')
    .noBucket()
    .noBlock()
*/
})